# Generated by Django 5.0.2 on 2024-04-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactsupport',
            name='user',
        ),
        migrations.AddField(
            model_name='contactsupport',
            name='name',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
